### ISSUE TITLE
Lawena windows are completely frozen

### ISSUE THREAD

**Issue by XenB100** [iabarca/lawena-recording-tool#80] opened 2016-03-22 17:02 UTC
Hey, I've been trying to get Lawena working for the past 2 days, I've redownloaded and reinstalled both java and the recording tool multiple times, I kept getting the same error. Every window Lawena opens up is totally frozen and I cannot click or change on anything at all.
What am I doing wrong?
Thanks in advance

![log](https://cloud.githubusercontent.com/assets/18012327/13960320/2c51ada4-f058-11e5-9d89-852909ef59f7.jpg)

**Comment by iabarca** [comment] 2016-03-22 17:06
Hey there, when you first start the program, does it ask you to locate your TF2 game folder?

Would also like to have the lawena.0.0.log file. If there isn't a file like that let me know.

**Comment by XenB100** [comment] 2016-03-22 17:11
It does not ask me to locate the TF2 game folder but instead it asks me where I want to store my recordings. The problem is that is cannot click or select anything on that window either, I can just press enter to proceed to the Lawena main menu or cancel the startup by clicking on the X on the top right corner of the window, these are the only thing that I can do.

![log0](https://cloud.githubusercontent.com/assets/18012327/13960610/5a0fa77c-f059-11e5-8fe3-675a29e03d63.jpg)

**Comment by iabarca** [comment] 2016-03-22 18:04
I don't know why you can't interact with the file chooser for recording folder. If you don't choose a recording folder Lawena won't let you interact with the main window (described by the last log you showed).

Can you edit the file ``settings.lwf`` with notepad and check for "MovieDir" line. Then add a full path to the folder. You might need to use `\:` instead of `:` and `\\` instead of `\`. For example
```properties
MovieDir=C\:\\Recordings
```

**Comment by XenB100** [comment] 2016-03-22 18:47
It already had its default path which I modified but still I cannot act or change anything in the main menu. Everything is frozen up and I can only close the program or move the window, nothing else. Could it be an issue with Java or something?

**Comment by iabarca** [comment] 2016-03-22 19:19
Could it be, but I only know of a similar issue happening with Windows 7 when using classic and not-Aero theme, and it causes the UI components to be misplaced and badly rendered, not plain unresponsiveness.

I've looked into this and it [might](http://stackoverflow.com/a/22791235) be related to 3D settings, GPU rendering quality or energy settings (requiring high performance mode for javaw.exe) causing this issue. Can't confirm since you haven't mentioned visual artifacts in the window.

Can you send me a screenshot of your main Lawena window when you can't interact with it, checking for visual glitches. If you move around the window do the contents turn and stay white? Also have you checked if keystrokes work? For instance hitting Tab to switch the component focus. Finally, how's the CPU usage of javaw.exe?

Thanks for reporting, with your response I'll gather more info to see if it's indeed related to Swing (java ui toolkit lawena v4 uses) + a certain combo of GPU settings.

**Comment by XenB100** [comment] 2016-03-22 20:23
Alright so basically moving the window gives no problems whatsoever and pressing Tab also changes focus with no issues of any kind. I can also change values (such as FPS) with the keyboard but I still cannot click or select anything.
Javaw.exe occupies around 80 MB of memory with Lawena running. Any clues?

![lawena](https://cloud.githubusercontent.com/assets/18012327/13966743/2bc6e23e-f074-11e5-9a9f-a0cdb6c68cd9.jpg)

**Comment by XenB100** [comment] 2016-03-24 12:46
Any news?

**Comment by iabarca** [comment] 2016-03-24 22:53
I don't understand how are you getting such a behavior -only able to interact with a couple of UI elements. One would imagine you would get a completely unresponsive application. I can't reproduce this at the moment.

I can only suggest you check for GPU settings in case some low power / energy saving mode is in place that could interfere with the app.

**Comment by iabarca** [comment] 2016-04-26 16:28
Closing as a way to archive this - I can't reproduce therefore I can't fix it

**Closed by iabarca** 2016-04-26 16:28 UTC
Labels: Bug, Needs Feedback
